---
- name: "Check if oh-my-zsh is installed"
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: debainStage2_zsh_installed

- name: "Execute provision/zsh.sh"
  ansible.builtin.script: resources/zsh/zsh.sh
  when: not debainStage2_zsh_installed.stat.exists

- name: "Copy .zshrc"
  ansible.builtin.copy:
    src: resources/zsh/.zshrc
    dest: ~/.zshrc
    mode: "0644"

- name: "Copy .p10k.zsh"
  ansible.builtin.copy:
    src: resources/zsh/.p10k.zsh
    dest: ~/.p10k.zsh
    mode: "0644"
