# Common
dns_domain: "{{ vault_dns_domain }}"

# Longhorn
longhorn_mtls_ca_crt: "{{ vault_longhorn_mtls_ca_crt }}"
longhorn_mtls_tls_crt: "{{ vault_longhorn_mtls_tsl_crt }}"
longhorn_mtls_tls_key: "{{ vault_longhorn_mtls_tls_key }}"
longhorn_crypto_key_value: "{{ vault_longhorn_crypto_key_value }}"

# Rook
rook_kms_key: "{{ vault_rook_kms_key }}"

# metallb
metallb_bgp_peer_ip: "{{ vault_metallb_bgp_peer_ip }}"
metallb_addreses: "{{ vault_metallb_addreses }}"
metallb_dns_address: "{{ vault_metallb_dns_address }}" 

# Traefik 
traefik_ip: "{{ vault_traefik_ip }}"

# Cert-manager
certManager_tsig_key: "{{ vault_certManager_tsig_key }}"
certManager_acme_server: "{{ vault_certManager_acme_server }}"
certManager_nameserver_ip: "{{ vault_certManager_nameserver_ip }}"

# External-dns
externalDns_nameserver_ip: "{{ vault_externalDns_nameserver_ip }}"
externalDns_tsig_key: "{{ vault_externalDns_tsig_key }}"
externalDns_dns_zone: "{{ vault_externalDns_dns_zone }}"
externalDns_tsig_key_name: "{{ vault_externalDns_tsig_key_name }}"
externalDns_tsig_key_algo: "{{ vault_externalDns_tsig_key_algo }}"

# Cilium
cilium_pod_cidr: "{{ vault_cilium_pod_cidr }}"
cilium_service_cidr: "{{ vault_cilium_service_cidr }}"
cilium_native_cidr: "{{ vault_cilium_native_cidr }}"
kubeadm_controlPlaneEndpoint_hostname: "{{ vault_kubeadm_controlPlaneEndpoint_hostname }}" # change in master group_vars too
kubeadm_api_port_lb: 7443 # change in master group_vars too