# Common
dns_domain: "{{ vault_dns_domain }}"

# Longhorn
longhorn_mtls_ca_crt: "{{ vault_longhorn_mtls_ca_crt }}"
longhorn_mtls_tls_crt: "{{ vault_longhorn_mtls_tsl_crt }}"
longhorn_mtls_tls_key: "{{ vault_longhorn_mtls_tls_key }}"
longhorn_crypto_key_value: "{{ vault_longhorn_crypto_key_value }}"

# metallb
metallb_bgp_peer_ip: "{{ vault_metallb_bgp_peer_ip }}"
metallb_addreses: "{{ vault_metallb_addreses }}"

# Traefik 
traefik_ip: "{{ vault_traefik_ip }}"

# Cert-manager
cert-manager_tsig_key: "{{ vault_cert-manager_tsig_key }}"
cert-manager_acme_server: "{{ vault_cert-manager_acme_server }}"
cert-manager_nameserver_ip: "{{ vault_cert-manager_nameserver_ip }}"

# External-dns
external-dns_nameserver_ip: "{{ vault_external-dns_nameserver_ip }}"
external-dns_tsig_key: "{{ vault_external-dns_tsig_key }}"
external-dns_dns_zone: "{{ vault_external-dns_dns_zone }}"
external-dns_tsig_key_name: "{{ vault_external-dns_tsig_key_name }}"
external-dns_tsig_key_algo: "{{ vault_external-dns_tsig_key_algo }}"

# Cilium
cilium_pod_cidr: "{{ vault_cilium_pod_cidr }}"
cilium_service_cidr: "{{ vault_cilium_service_cidr }}"
cilium_native_cidr: "{{ vault_cilium_native_cidr }}"