---
- name: "Add docker repo"
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts.distribution_release }}"
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: "Install docker"
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - containerd.io
      - golang-github-containerd-go-cni-dev
      - golang-github-containerd-go-runc-dev
